### PR TITLE
Avoid logging errors when expanding a variable with a null context (resolves #124)

### LINKED ISSUE #124: Calling opentracing_propagate_context throws an error when opentracing is off
We have opentracing switched on or off in different environments, controlled by an environmental variable. When opentracing is switched off the code in nginx.conf is essentially this:

```
load_module modules/ngx_http_opentracing_module.so;
http {
   opentracing_load_tracer /usr/local/lib/libjaegertracing_plugin.so /srv/src/main/resources/jaeger-nginx-config.json;
   opentracing off;
   upstream backend {
      server app-service:9001;
   }
   location ~ {
     opentracing_propagate_context;
     proxy_pass http://backend;
   }
}
```
However, the call: opentracing_propagate_context causes the following error to be logged for every request:

```
[error] 52#52: *31049 failed to expand opentracing_context_ for request 0000000001D58EB0: no OpenTracingContext attached to request
```
If opentracing is off, shouldn't this message be suppressed?

Mike

### PR DESCRIPTION
**Pull request by verdie-g**
When opentracing is set to off in the nginx configuration and if an opentracing variable was used, get_opentracing_context would return null during its expansion and an error was logged. Instead I think a NGX_ERROR should be returned so the variable is expanded to '-'.

Also I made sure the full variable name is logged instead of only the prefix (`opentracing_context_x_datadog_trace_id` instead of `opentracing_context_`). The logs now look like
```
2021/02/02 13:08:05 [debug] 88#0: *1 failed to expand opentracing_context_x_datadog_trace_id: no OpenTracingContext attached to request 000055F1CEF07070
2021/02/02 13:08:05 [debug] 88#0: *1 failed to expand opentracing_context_x_datadog_parent_id: no OpenTracingContext attached to request 000055F1CEF07070
```
when it was
```
2021/01/26 18:48:08 [error] 7136#0: *1 failed to expand opentracing_context_ for request 000056053B46F110: no OpenTracingContext attached to request 000055F1CEF07070
2021/01/26 18:48:08 [error] 7136#0: *1 failed to expand opentracing_context_ for request 000056053B46F110: no OpenTracingContext attached to request 000055F1CEF07070
```

### CODE REVIEW

**Comment by miry** [comment]
@verdie-g Pls rebase against master.

**Comment by verdie-g** [comment]
@miry Done!

**Comment by miry** [comment]
@verdie-g Can you update the example how the logs would looks like.

**Comment by verdie-g** [comment]
@miry I added a log example in the PR description.

**Comment by miry** [comment]
❤️

**Comment by miry** [comment]
@verdie-g released with this changes in https://github.com/opentracing-contrib/nginx-opentracing/releases/edit/v0.12.0

**Pull request merged**
