### PR TITLE
Add Datadog nginx tracing example

### PR DESCRIPTION
**Pull request by willgittoes-dd**
Adds a Datadog version of the 'trivial' example.

- Adds example/trivial/datadog folder
- Updates ./Dockerfile to build the Datadog C++ OpenTracing implementation
- Adds Datadog info to the README

Does not yet:

- Add support for OpenResty

_Thank you kindly to rnburn and others for creating nginx-opentracing!_

### CODE REVIEW

**Comment by rnburn** [comment]
Thanks - btw it looks like your [method](https://github.com/DataDog/dd-opentracing-cpp/blob/master/src/tracer.cpp#L13-L17) of generating ids is going to run into this issue https://github.com/opentracing-contrib/nginx-opentracing/issues/52

This is how I fixed it for the other tracers: https://github.com/lightstep/lightstep-tracer-cpp/pull/110

**Comment by willgittoes-dd** [comment]
Pretty sure we were half way through trying to find out where some "missing spans" were going, so once again you've saved us a great amount of time :)

**Comment by willgittoes-dd** [comment]
(and docker_image fail is due to unmerged PR on our end. I developed against a different tag not the one mentioned as ARG DATADOG_VERSION)

**Comment by rnburn** [comment]
Looks good. Was there anything else you wanted to add or should I go ahead and merge?

**Comment by willgittoes-dd** [comment]
Not for now; at some point I'll update the lua-bridge and then I can send an OpenResty PR. 

Thanks again for all your help!

**Pull request merged**
