### PR TITLE
Build modules for Nginx 1.27.0

### PR DESCRIPTION
**Pull request by oseoin**
Also added 1.26.1.

### CODE REVIEW

**Comment by oseoin** [comment]
Not sure if the intention is to keep multiple point releases for each version, happy to clean up 1.25 and 1.26 to only use the latest as part of this PR if needed @miry? Thanks!

**Comment by miry** [comment]
@oseoin If you can cleanup, it would be nice.

**Review by lucacome — CHANGES_REQUESTED** [review]
I think we should leave 1.26.0 since it's pretty new

**Review by lucacome — APPROVED** [review]

**Comment by miry** [comment]
released a new version with new nginx modules: https://github.com/opentracing-contrib/nginx-opentracing/releases/tag/v0.35.2

**Pull request merged**
