### PR TITLE
Support Nginx v1.20.0 and v.1.20.1

### PR DESCRIPTION
**Pull request by nothinux**
added support for nginx version 1.20.0 and 1.20.1

### CODE REVIEW

**Comment by miry** [comment]
Sorry have not released yet.

**Comment by return-nil** [comment]
When will it be released?🥺

**Comment by miry** [comment]
released https://github.com/opentracing-contrib/nginx-opentracing/releases/tag/v0.17.0

**Comment by nothinux** [comment]
Thank you @miry

**Pull request merged**
