### PR TITLE
Cross-compile libraries

### PR DESCRIPTION
**Pull request by lucacome**
- Cross-compile libraries leveraging helper tools from https://github.com/tonistiigi/xx
- Remove gRPC build (doesn't seem to be used)
- Build plugin directly for zipkin, jaeger and datadog
- Avoid building unnecessary files for jaeger

### CODE REVIEW

**Comment by lucacome** [comment]
Well, my main goal (other than supporting s390x) was to improve building time but seems like gRPC still takes forever. What is it needed for?

**Comment by miry** [comment]
As I remember it was used for some of the adpater Lightstep or Jaeger.

**Comment by lucacome** [comment]
Ah yeah seems like it’s required for Lightstep (even though not in the latest version). Should I disable the build for now since Lightstep is not being built and the other tracer don’t use it (it’s in a different stage that non of the other use)?

**Comment by miry** [comment]
@lucacome There is also zipkin-cpp that requires grpc: https://github.com/flier/zipkin-cpp/blob/master/CMakeLists.txt#L58

**Comment by lucacome** [comment]
Interesting, it wasn't complaining when I tried to disable the build for gRPC...

**Comment by lucacome** [comment]
@miry I think that's a different repo for zipkin, this uses https://github.com/rnburn/zipkin-cpp-opentracing.git ?

**Comment by lucacome** [comment]
I've updated this PR to cross-compile libraries and commented out gRPC since it's not used at the moment (and causes problems)

**Review by miry — APPROVED** [review]

**Pull request merged**
