### PR TITLE
Build modules for NGINX 1.25.4

### PR DESCRIPTION
**Pull request by lucacome**
Adds build for `1.25.4`

### CODE REVIEW

**Review by pdabelf5 — APPROVED** [review]

**Review by miry — APPROVED** [review]

**Comment by miry** [comment]
It seems I merged to early.
May be I forgot the process.

Should ci/build_module_binaries.sh be updated as well?

**Comment by miry** [comment]
I see we want to build for platform:,

but there is no image with this platform in https://hub.docker.com/layers/library/nginx/1.25.4/images/sha256-05aa73005987caaed48ea8213696b0df761ccd600d2c53fc0a1a97a180301d71?context=explore&tab=vulnerabilities

image

**Comment by lucacome** [comment]
I don't think we would want to release different architectures, we probably want to wait for docker hub to fix this if it happens in the future.
I was already thinking about changing the build in the PR so that it builds for all platforms all the time, I guess this is giving me the nudge I needed 😄

**Comment by miry** [comment]
Also make sense. It could parse branch name or PR to run all platforms.

**Pull request merged**
